AWS_ACCESS_KEY_ID_ENV_KEY = "AWS_ACCESS_KEY_ID"
AWS_SECRET_ACCESS_KEY_ENV_KEY = "AWS_SECRET_ACCESS_KEY"
AWS_REGION = "AWS_REGION_NAME"
S3_BUCKET = "MODEL_BUCKET_NAME"

DAGSHUB_TOKEN = "DAGSHUB_REPO_TOKEN"