# Environment Variable Keys
AWS_ACCESS_KEY_ID_ENV_KEY = "AWS_ACCESS_KEY_ID"
AWS_SECRET_ACCESS_KEY_ENV_KEY = "AWS_SECRET_ACCESS_KEY"
AWS_REGION_ENV_KEY = "AWS_REGION"
S3_BUCKET_ENV_KEY = "S3_BUCKET_NAME"

DAGSHUB_TOKEN_ENV_KEY = "DAGSHUB_TOKEN"